### ISSUE TITLE
Could you please explain how to use this?

### ISSUE THREAD

**Issue by at2008** [FlipperPA/wagtailmarkdownblock#9]
I used wagtail2.3 version.
Everything was fine when editing the article in admin area, but after the article was published, the markdown displayed was abnormal. Could you please explain how to use this?

**Comment by FlipperPA** [comment]
Hi @at2008, we've stopped development on this package as Markdown is now supported in the Draftail editor. See at the top of the README:

`PLEASE NOTE: Future development on this package will be limited, since most of the features are now included in the new Draftail editor available in Wagtail. Thank you to everyone who contributed!`

**Comment by at2008** [comment]
> Hi @at2008, we've stopped development on this package as Markdown is now supported in the Draftail editor. See at the top of the README:
> 
> `PLEASE NOTE: Future development on this package will be limited, since most of the features are now included in the new Draftail editor available in Wagtail. Thank you to everyone who contributed!`

Thank you for your reply. Good luck.
